HM to sprint 8
Call-of-Arreat/java-kanban pull request #3
Opened 2024-09-11 20:32 UTC by Call-of-Arreat

2024-09-12 03:42 UTC, sergeymamonov requested changes

2024-09-12 03:42 UTC, sergeymamonov commented on src/manager/InMemoryTaskManager.java
> +    protected Set<Task> prioritized = new TreeSet<>(Comparator.comparing(Task::getStartTime));
Зачем протектед, если обращаются к этому множеству только из этого класса?

2024-09-12 03:42 UTC, sergeymamonov commented on src/manager/TaskManager.java
>      int generateId();
Не нужно этот метод выносить в интерфейс. Это же внутренний метод. Его даже никто не использует.

2024-09-12 03:42 UTC, sergeymamonov commented on src/tasks/Epic.java
> +    public Epic(String name, String taskDescription, Duration duration, LocalDateTime startTime,
В коде не должно быть неиспользуемых методов, переменных и так далее.

2024-09-12 03:42 UTC, sergeymamonov commented on src/tasks/Task.java
>      public Task(String taskName, String taskDescription, Status taskStatus) {
Аргумент taskStatus не используется в конструкторе.

2024-09-13 11:48 UTC, Call-of-Arreat commented on src/manager/InMemoryTaskManager.java
> +    protected Set<Task> prioritized = new TreeSet<>(Comparator.comparing(Task::getStartTime));
Поправил

2024-09-13 11:49 UTC, Call-of-Arreat commented on src/manager/TaskManager.java
>      int generateId();
Удалил неиспользуемый метод из проекта

2024-09-13 11:50 UTC, Call-of-Arreat commented on src/tasks/Epic.java
> +    public Epic(String name, String taskDescription, Duration duration, LocalDateTime startTime,
Удалил неиспользуемый конструктор

2024-09-13 13:20 UTC, Call-of-Arreat commented on src/tasks/Task.java
>      public Task(String taskName, String taskDescription, Status taskStatus) {
Удалил

2024-09-14 04:32 UTC, sergeymamonov approved these changes

2024-09-14 07:37 UTC, merged